#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ data.values.name
  namespace: #@ data.values.namespace
data:
  APP_ENVIRONMENT: "test"
  APP_NAME: "shareable-api-ytt"
  AUTOMIGRATE: "false"
  PORT: #@ str(data.values.port)

