#@ load("@ytt:data", "data")
#@ if data.values.ingress.enabled:
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: #@ data.values.name
  namespace: #@ data.values.namespace
spec:
  rules:
    - host: #@ data.values.ingress.host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: #@ data.values.name
                port:
                  number: #@ data.values.port
#@ end

