#@data/values
---
name: sharable-api-with-ytt
namespace: sharable

image: europe-west8-docker.pkg.dev/spinning-rust/reg/sportpesa/global/shareable-api:1.2.0
replicas: 1
port: 3000

metrics:
  enabled: true
  path: /metrics
  port: "3000"

ingress:
  enabled: true
  host: sharable-api.test.internal

